create table ZIP (
	city VARCHAR(50),
	state VARCHAR(50)
);
insert into ZIP (city, state) values ('Detroit', 'Michigan');
insert into ZIP (city, state) values ('Greensboro', 'North Carolina');
insert into ZIP (city, state) values ('Independence', 'Missouri');
insert into ZIP (city, state) values ('Merrifield', 'Virginia');
insert into ZIP (city, state) values ('Chattanooga', 'Tennessee');
insert into ZIP (city, state) values ('Kalamazoo', 'Michigan');
insert into ZIP (city, state) values ('Huntington', 'West Virginia');
insert into ZIP (city, state) values ('Lafayette', 'Louisiana');
insert into ZIP (city, state) values ('Charleston', 'West Virginia');
insert into ZIP (city, state) values ('Austin', 'Texas');
insert into ZIP (city, state) values ('Salt Lake City', 'Utah');
insert into ZIP (city, state) values ('Jacksonville', 'Florida');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Indianapolis', 'Indiana');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Fort Myers', 'Florida');
insert into ZIP (city, state) values ('Everett', 'Washington');
insert into ZIP (city, state) values ('Pasadena', 'California');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Farmington', 'Michigan');
insert into ZIP (city, state) values ('Buffalo', 'New York');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Appleton', 'Wisconsin');
insert into ZIP (city, state) values ('Harrisburg', 'Pennsylvania');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Portland', 'Oregon');
insert into ZIP (city, state) values ('Decatur', 'Illinois');
insert into ZIP (city, state) values ('Fort Worth', 'Texas');
insert into ZIP (city, state) values ('New Bedford', 'Massachusetts');
insert into ZIP (city, state) values ('Gainesville', 'Florida');
insert into ZIP (city, state) values ('Juneau', 'Alaska');
insert into ZIP (city, state) values ('Aurora', 'Colorado');
insert into ZIP (city, state) values ('Jackson', 'Mississippi');
insert into ZIP (city, state) values ('Columbia', 'South Carolina');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Iowa City', 'Iowa');
insert into ZIP (city, state) values ('Birmingham', 'Alabama');
insert into ZIP (city, state) values ('Birmingham', 'Alabama');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Norman', 'Oklahoma');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Gainesville', 'Florida');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('Cincinnati', 'Ohio');
insert into ZIP (city, state) values ('Jamaica', 'New York');
insert into ZIP (city, state) values ('Stamford', 'Connecticut');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Madison', 'Wisconsin');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Boise', 'Idaho');
insert into ZIP (city, state) values ('Charleston', 'West Virginia');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('Springfield', 'Missouri');
insert into ZIP (city, state) values ('Metairie', 'Louisiana');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Fort Worth', 'Texas');
insert into ZIP (city, state) values ('Wilmington', 'North Carolina');
insert into ZIP (city, state) values ('Vero Beach', 'Florida');
insert into ZIP (city, state) values ('Aurora', 'Colorado');
insert into ZIP (city, state) values ('Fresno', 'California');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Syracuse', 'New York');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Conroe', 'Texas');
insert into ZIP (city, state) values ('Ventura', 'California');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('North Little Rock', 'Arkansas');
insert into ZIP (city, state) values ('Lexington', 'Kentucky');
insert into ZIP (city, state) values ('Canton', 'Ohio');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Lexington', 'Kentucky');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Sarasota', 'Florida');
insert into ZIP (city, state) values ('Jackson', 'Mississippi');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Kansas City', 'Kansas');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Omaha', 'Nebraska');
insert into ZIP (city, state) values ('Lawrenceville', 'Georgia');
insert into ZIP (city, state) values ('Corona', 'California');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Jackson', 'Mississippi');
insert into ZIP (city, state) values ('Vero Beach', 'Florida');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Olympia', 'Washington');
insert into ZIP (city, state) values ('Greensboro', 'North Carolina');
insert into ZIP (city, state) values ('Denton', 'Texas');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Wichita', 'Kansas');
insert into ZIP (city, state) values ('Irvine', 'California');
insert into ZIP (city, state) values ('North Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Shawnee Mission', 'Kansas');
insert into ZIP (city, state) values ('Chicago', 'Illinois');
insert into ZIP (city, state) values ('Canton', 'Ohio');
insert into ZIP (city, state) values ('Corpus Christi', 'Texas');
insert into ZIP (city, state) values ('Spring', 'Texas');
insert into ZIP (city, state) values ('Oklahoma City', 'Oklahoma');
insert into ZIP (city, state) values ('Boston', 'Massachusetts');
insert into ZIP (city, state) values ('Midland', 'Texas');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('Salem', 'Oregon');
insert into ZIP (city, state) values ('Muskegon', 'Michigan');
insert into ZIP (city, state) values ('Shreveport', 'Louisiana');
insert into ZIP (city, state) values ('Harrisburg', 'Pennsylvania');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Portland', 'Maine');
insert into ZIP (city, state) values ('Naples', 'Florida');
insert into ZIP (city, state) values ('Chandler', 'Arizona');
insert into ZIP (city, state) values ('Daytona Beach', 'Florida');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('Carol Stream', 'Illinois');
insert into ZIP (city, state) values ('Albany', 'Georgia');
insert into ZIP (city, state) values ('Charlotte', 'North Carolina');
insert into ZIP (city, state) values ('Portland', 'Oregon');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Fresno', 'California');
insert into ZIP (city, state) values ('Arlington', 'Virginia');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Lake Charles', 'Louisiana');
insert into ZIP (city, state) values ('Mesquite', 'Texas');
insert into ZIP (city, state) values ('Saint Cloud', 'Minnesota');
insert into ZIP (city, state) values ('Birmingham', 'Alabama');
insert into ZIP (city, state) values ('Omaha', 'Nebraska');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Clearwater', 'Florida');
insert into ZIP (city, state) values ('Indianapolis', 'Indiana');
insert into ZIP (city, state) values ('Richmond', 'Virginia');
insert into ZIP (city, state) values ('Wichita', 'Kansas');
insert into ZIP (city, state) values ('Canton', 'Ohio');
insert into ZIP (city, state) values ('Englewood', 'Colorado');
insert into ZIP (city, state) values ('Jackson', 'Tennessee');
insert into ZIP (city, state) values ('Trenton', 'New Jersey');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Carol Stream', 'Illinois');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Durham', 'North Carolina');
insert into ZIP (city, state) values ('Fairfax', 'Virginia');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Beaufort', 'South Carolina');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Fort Worth', 'Texas');
insert into ZIP (city, state) values ('Wichita', 'Kansas');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('New Orleans', 'Louisiana');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Pueblo', 'Colorado');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Richmond', 'Virginia');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Lincoln', 'Nebraska');
insert into ZIP (city, state) values ('Reno', 'Nevada');
insert into ZIP (city, state) values ('Kalamazoo', 'Michigan');
insert into ZIP (city, state) values ('Irvine', 'California');
insert into ZIP (city, state) values ('Inglewood', 'California');
insert into ZIP (city, state) values ('Gastonia', 'North Carolina');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Lincoln', 'Nebraska');
insert into ZIP (city, state) values ('Indianapolis', 'Indiana');
insert into ZIP (city, state) values ('South Bend', 'Indiana');
insert into ZIP (city, state) values ('Plano', 'Texas');
insert into ZIP (city, state) values ('Nashville', 'Tennessee');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Anchorage', 'Alaska');
insert into ZIP (city, state) values ('Bakersfield', 'California');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Tucson', 'Arizona');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Roanoke', 'Virginia');
insert into ZIP (city, state) values ('Santa Monica', 'California');
insert into ZIP (city, state) values ('Norcross', 'Georgia');
insert into ZIP (city, state) values ('San Bernardino', 'California');
insert into ZIP (city, state) values ('Lafayette', 'Louisiana');
insert into ZIP (city, state) values ('New Orleans', 'Louisiana');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Dearborn', 'Michigan');
insert into ZIP (city, state) values ('Greenville', 'South Carolina');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('Fort Worth', 'Texas');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Youngstown', 'Ohio');
insert into ZIP (city, state) values ('Macon', 'Georgia');
insert into ZIP (city, state) values ('Anchorage', 'Alaska');
insert into ZIP (city, state) values ('Vancouver', 'Washington');
insert into ZIP (city, state) values ('Charleston', 'West Virginia');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Akron', 'Ohio');
insert into ZIP (city, state) values ('Alpharetta', 'Georgia');
insert into ZIP (city, state) values ('Saint Paul', 'Minnesota');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('Lees Summit', 'Missouri');
insert into ZIP (city, state) values ('Davenport', 'Iowa');
insert into ZIP (city, state) values ('Boulder', 'Colorado');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('Lake Worth', 'Florida');
insert into ZIP (city, state) values ('Madison', 'Wisconsin');
insert into ZIP (city, state) values ('Lancaster', 'Pennsylvania');
insert into ZIP (city, state) values ('Wichita', 'Kansas');
insert into ZIP (city, state) values ('Austin', 'Texas');
insert into ZIP (city, state) values ('Anderson', 'Indiana');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Meridian', 'Mississippi');
insert into ZIP (city, state) values ('Chicago', 'Illinois');
insert into ZIP (city, state) values ('Anaheim', 'California');
insert into ZIP (city, state) values ('Tallahassee', 'Florida');
insert into ZIP (city, state) values ('White Plains', 'New York');
insert into ZIP (city, state) values ('New Haven', 'Connecticut');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Newark', 'New Jersey');
insert into ZIP (city, state) values ('Trenton', 'New Jersey');
insert into ZIP (city, state) values ('Staten Island', 'New York');
insert into ZIP (city, state) values ('Midland', 'Michigan');
insert into ZIP (city, state) values ('Clearwater', 'Florida');
insert into ZIP (city, state) values ('Van Nuys', 'California');
insert into ZIP (city, state) values ('Oxnard', 'California');
insert into ZIP (city, state) values ('Henderson', 'Nevada');
insert into ZIP (city, state) values ('San Jose', 'California');
insert into ZIP (city, state) values ('Boston', 'Massachusetts');
insert into ZIP (city, state) values ('Salt Lake City', 'Utah');
insert into ZIP (city, state) values ('Nashville', 'Tennessee');
insert into ZIP (city, state) values ('Columbia', 'South Carolina');
insert into ZIP (city, state) values ('Alexandria', 'Virginia');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Spokane', 'Washington');
insert into ZIP (city, state) values ('Santa Ana', 'California');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Toledo', 'Ohio');
insert into ZIP (city, state) values ('San Jose', 'California');
insert into ZIP (city, state) values ('Saint Petersburg', 'Florida');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Irvine', 'California');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Fort Myers', 'Florida');
insert into ZIP (city, state) values ('Wichita', 'Kansas');
insert into ZIP (city, state) values ('Canton', 'Ohio');
insert into ZIP (city, state) values ('Greenville', 'South Carolina');
insert into ZIP (city, state) values ('Lakeland', 'Florida');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('Akron', 'Ohio');
insert into ZIP (city, state) values ('Virginia Beach', 'Virginia');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Port Charlotte', 'Florida');
insert into ZIP (city, state) values ('East Saint Louis', 'Illinois');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Utica', 'New York');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Dayton', 'Ohio');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Kansas City', 'Kansas');
insert into ZIP (city, state) values ('Detroit', 'Michigan');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Rochester', 'New York');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Hialeah', 'Florida');
insert into ZIP (city, state) values ('Fort Worth', 'Texas');
insert into ZIP (city, state) values ('Inglewood', 'California');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Escondido', 'California');
insert into ZIP (city, state) values ('Amarillo', 'Texas');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Erie', 'Pennsylvania');
insert into ZIP (city, state) values ('Columbia', 'Missouri');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('Lexington', 'Kentucky');
insert into ZIP (city, state) values ('Garland', 'Texas');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Fredericksburg', 'Virginia');
insert into ZIP (city, state) values ('Berkeley', 'California');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Corpus Christi', 'Texas');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Anderson', 'South Carolina');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Tallahassee', 'Florida');
insert into ZIP (city, state) values ('Columbus', 'Georgia');
insert into ZIP (city, state) values ('Yakima', 'Washington');
insert into ZIP (city, state) values ('Norfolk', 'Virginia');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Fresno', 'California');
insert into ZIP (city, state) values ('Aurora', 'Colorado');
insert into ZIP (city, state) values ('Staten Island', 'New York');
insert into ZIP (city, state) values ('Springfield', 'Illinois');
insert into ZIP (city, state) values ('Athens', 'Georgia');
insert into ZIP (city, state) values ('Orlando', 'Florida');
insert into ZIP (city, state) values ('Naples', 'Florida');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Panama City', 'Florida');
insert into ZIP (city, state) values ('Portland', 'Oregon');
insert into ZIP (city, state) values ('Port Washington', 'New York');
insert into ZIP (city, state) values ('Sunnyvale', 'California');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Carol Stream', 'Illinois');
insert into ZIP (city, state) values ('Murfreesboro', 'Tennessee');
insert into ZIP (city, state) values ('Tampa', 'Florida');
insert into ZIP (city, state) values ('Huntington', 'West Virginia');
insert into ZIP (city, state) values ('Akron', 'Ohio');
insert into ZIP (city, state) values ('Greensboro', 'North Carolina');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Springfield', 'Virginia');
insert into ZIP (city, state) values ('Brea', 'California');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Raleigh', 'North Carolina');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Bradenton', 'Florida');
insert into ZIP (city, state) values ('Albany', 'New York');
insert into ZIP (city, state) values ('Shawnee Mission', 'Kansas');
insert into ZIP (city, state) values ('Wilkes Barre', 'Pennsylvania');
insert into ZIP (city, state) values ('Portsmouth', 'New Hampshire');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Columbus', 'Ohio');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Albany', 'New York');
insert into ZIP (city, state) values ('Green Bay', 'Wisconsin');
insert into ZIP (city, state) values ('Hagerstown', 'Maryland');
insert into ZIP (city, state) values ('Bradenton', 'Florida');
insert into ZIP (city, state) values ('Orlando', 'Florida');
insert into ZIP (city, state) values ('Pasadena', 'California');
insert into ZIP (city, state) values ('Bakersfield', 'California');
insert into ZIP (city, state) values ('Portland', 'Oregon');
insert into ZIP (city, state) values ('Shawnee Mission', 'Kansas');
insert into ZIP (city, state) values ('Waco', 'Texas');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Arlington', 'Texas');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Crawfordsville', 'Indiana');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Stamford', 'Connecticut');
insert into ZIP (city, state) values ('Lake Worth', 'Florida');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Birmingham', 'Alabama');
insert into ZIP (city, state) values ('Norfolk', 'Virginia');
insert into ZIP (city, state) values ('Omaha', 'Nebraska');
insert into ZIP (city, state) values ('Tulsa', 'Oklahoma');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Saint Paul', 'Minnesota');
insert into ZIP (city, state) values ('Columbia', 'Missouri');
insert into ZIP (city, state) values ('Omaha', 'Nebraska');
insert into ZIP (city, state) values ('South Lake Tahoe', 'California');
insert into ZIP (city, state) values ('Newton', 'Massachusetts');
insert into ZIP (city, state) values ('Bakersfield', 'California');
insert into ZIP (city, state) values ('Columbus', 'Mississippi');
insert into ZIP (city, state) values ('Fredericksburg', 'Virginia');
insert into ZIP (city, state) values ('Chicago', 'Illinois');
insert into ZIP (city, state) values ('Birmingham', 'Alabama');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Roanoke', 'Virginia');
insert into ZIP (city, state) values ('Ashburn', 'Virginia');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Oxnard', 'California');
insert into ZIP (city, state) values ('Topeka', 'Kansas');
insert into ZIP (city, state) values ('Greensboro', 'North Carolina');
insert into ZIP (city, state) values ('Fargo', 'North Dakota');
insert into ZIP (city, state) values ('Staten Island', 'New York');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Scottsdale', 'Arizona');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Stockton', 'California');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Tampa', 'Florida');
insert into ZIP (city, state) values ('Green Bay', 'Wisconsin');
insert into ZIP (city, state) values ('Murfreesboro', 'Tennessee');
insert into ZIP (city, state) values ('Chattanooga', 'Tennessee');
insert into ZIP (city, state) values ('Santa Cruz', 'California');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Charleston', 'West Virginia');
insert into ZIP (city, state) values ('Newton', 'Massachusetts');
insert into ZIP (city, state) values ('Naperville', 'Illinois');
insert into ZIP (city, state) values ('Bethesda', 'Maryland');
insert into ZIP (city, state) values ('Virginia Beach', 'Virginia');
insert into ZIP (city, state) values ('Tyler', 'Texas');
insert into ZIP (city, state) values ('Fresno', 'California');
insert into ZIP (city, state) values ('Albany', 'New York');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Trenton', 'New Jersey');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Scottsdale', 'Arizona');
insert into ZIP (city, state) values ('Wichita Falls', 'Texas');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Birmingham', 'Alabama');
insert into ZIP (city, state) values ('Chicago', 'Illinois');
insert into ZIP (city, state) values ('Winston Salem', 'North Carolina');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Anchorage', 'Alaska');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('San Bernardino', 'California');
insert into ZIP (city, state) values ('Naperville', 'Illinois');
insert into ZIP (city, state) values ('Harrisburg', 'Pennsylvania');
insert into ZIP (city, state) values ('Bakersfield', 'California');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Vancouver', 'Washington');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Madison', 'Wisconsin');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Ocala', 'Florida');
insert into ZIP (city, state) values ('Paterson', 'New Jersey');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Pasadena', 'Texas');
insert into ZIP (city, state) values ('Decatur', 'Georgia');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Staten Island', 'New York');
insert into ZIP (city, state) values ('Peoria', 'Illinois');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('Tucson', 'Arizona');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Boulder', 'Colorado');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Arlington', 'Texas');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Worcester', 'Massachusetts');
insert into ZIP (city, state) values ('Mesa', 'Arizona');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Fort Worth', 'Texas');
insert into ZIP (city, state) values ('Columbia', 'South Carolina');
insert into ZIP (city, state) values ('Shreveport', 'Louisiana');
insert into ZIP (city, state) values ('Staten Island', 'New York');
insert into ZIP (city, state) values ('Peoria', 'Illinois');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Tulsa', 'Oklahoma');
insert into ZIP (city, state) values ('Punta Gorda', 'Florida');
insert into ZIP (city, state) values ('Flint', 'Michigan');
insert into ZIP (city, state) values ('Albany', 'New York');
insert into ZIP (city, state) values ('Albany', 'New York');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Chicago', 'Illinois');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Providence', 'Rhode Island');
insert into ZIP (city, state) values ('Baton Rouge', 'Louisiana');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Idaho Falls', 'Idaho');
insert into ZIP (city, state) values ('Buffalo', 'New York');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('Naples', 'Florida');
insert into ZIP (city, state) values ('Springfield', 'Missouri');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('Jefferson City', 'Missouri');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('North Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Rochester', 'New York');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Bronx', 'New York');
insert into ZIP (city, state) values ('Boston', 'Massachusetts');
insert into ZIP (city, state) values ('Conroe', 'Texas');
insert into ZIP (city, state) values ('Paterson', 'New Jersey');
insert into ZIP (city, state) values ('Portland', 'Oregon');
insert into ZIP (city, state) values ('Kansas City', 'Missouri');
insert into ZIP (city, state) values ('Huntsville', 'Alabama');
insert into ZIP (city, state) values ('New Haven', 'Connecticut');
insert into ZIP (city, state) values ('Tyler', 'Texas');
insert into ZIP (city, state) values ('Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Hampton', 'Virginia');
insert into ZIP (city, state) values ('Durham', 'North Carolina');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Troy', 'Michigan');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Amarillo', 'Texas');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('South Bend', 'Indiana');
insert into ZIP (city, state) values ('Brockton', 'Massachusetts');
insert into ZIP (city, state) values ('New Orleans', 'Louisiana');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Spokane', 'Washington');
insert into ZIP (city, state) values ('Tucson', 'Arizona');
insert into ZIP (city, state) values ('Tampa', 'Florida');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('Saginaw', 'Michigan');
insert into ZIP (city, state) values ('Columbus', 'Ohio');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Fort Wayne', 'Indiana');
insert into ZIP (city, state) values ('Nashville', 'Tennessee');
insert into ZIP (city, state) values ('Long Beach', 'California');
insert into ZIP (city, state) values ('Austin', 'Texas');
insert into ZIP (city, state) values ('Albany', 'New York');
insert into ZIP (city, state) values ('Metairie', 'Louisiana');
insert into ZIP (city, state) values ('Spring', 'Texas');
insert into ZIP (city, state) values ('Chicago', 'Illinois');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Waterbury', 'Connecticut');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Birmingham', 'Alabama');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Largo', 'Florida');
insert into ZIP (city, state) values ('Topeka', 'Kansas');
insert into ZIP (city, state) values ('Brockton', 'Massachusetts');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('White Plains', 'New York');
insert into ZIP (city, state) values ('Amarillo', 'Texas');
insert into ZIP (city, state) values ('Lansing', 'Michigan');
insert into ZIP (city, state) values ('Knoxville', 'Tennessee');
insert into ZIP (city, state) values ('Spring', 'Texas');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Duluth', 'Minnesota');
insert into ZIP (city, state) values ('Tucson', 'Arizona');
insert into ZIP (city, state) values ('Terre Haute', 'Indiana');
insert into ZIP (city, state) values ('Long Beach', 'California');
insert into ZIP (city, state) values ('Flint', 'Michigan');
insert into ZIP (city, state) values ('Memphis', 'Tennessee');
insert into ZIP (city, state) values ('Rockford', 'Illinois');
insert into ZIP (city, state) values ('Young America', 'Minnesota');
insert into ZIP (city, state) values ('Zephyrhills', 'Florida');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Columbus', 'Ohio');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('Humble', 'Texas');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Cincinnati', 'Ohio');
insert into ZIP (city, state) values ('Macon', 'Georgia');
insert into ZIP (city, state) values ('Greensboro', 'North Carolina');
insert into ZIP (city, state) values ('Everett', 'Washington');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Columbus', 'Ohio');
insert into ZIP (city, state) values ('Baton Rouge', 'Louisiana');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Watertown', 'Massachusetts');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('Boca Raton', 'Florida');
insert into ZIP (city, state) values ('Littleton', 'Colorado');
insert into ZIP (city, state) values ('Orange', 'California');
insert into ZIP (city, state) values ('Odessa', 'Texas');
insert into ZIP (city, state) values ('Springfield', 'Massachusetts');
insert into ZIP (city, state) values ('Stamford', 'Connecticut');
insert into ZIP (city, state) values ('Ridgely', 'Maryland');
insert into ZIP (city, state) values ('Torrance', 'California');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Pueblo', 'Colorado');
insert into ZIP (city, state) values ('Springfield', 'Illinois');
insert into ZIP (city, state) values ('Lafayette', 'Louisiana');
insert into ZIP (city, state) values ('Largo', 'Florida');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Hartford', 'Connecticut');
insert into ZIP (city, state) values ('Shreveport', 'Louisiana');
insert into ZIP (city, state) values ('Brooklyn', 'New York');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Corpus Christi', 'Texas');
insert into ZIP (city, state) values ('Duluth', 'Georgia');
insert into ZIP (city, state) values ('Arlington', 'Virginia');
insert into ZIP (city, state) values ('Charlotte', 'North Carolina');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Charleston', 'West Virginia');
insert into ZIP (city, state) values ('Levittown', 'Pennsylvania');
insert into ZIP (city, state) values ('Fort Pierce', 'Florida');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Springfield', 'Massachusetts');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Cincinnati', 'Ohio');
insert into ZIP (city, state) values ('Garden Grove', 'California');
insert into ZIP (city, state) values ('New Brunswick', 'New Jersey');
insert into ZIP (city, state) values ('Baton Rouge', 'Louisiana');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Hartford', 'Connecticut');
insert into ZIP (city, state) values ('Nashville', 'Tennessee');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Irvine', 'California');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Buffalo', 'New York');
insert into ZIP (city, state) values ('Largo', 'Florida');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Saint Paul', 'Minnesota');
insert into ZIP (city, state) values ('Amarillo', 'Texas');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Reston', 'Virginia');
insert into ZIP (city, state) values ('Beaverton', 'Oregon');
insert into ZIP (city, state) values ('Corpus Christi', 'Texas');
insert into ZIP (city, state) values ('Huntington', 'West Virginia');
insert into ZIP (city, state) values ('Santa Barbara', 'California');
insert into ZIP (city, state) values ('Bryan', 'Texas');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Savannah', 'Georgia');
insert into ZIP (city, state) values ('Youngstown', 'Ohio');
insert into ZIP (city, state) values ('Memphis', 'Tennessee');
insert into ZIP (city, state) values ('Valley Forge', 'Pennsylvania');
insert into ZIP (city, state) values ('Toledo', 'Ohio');
insert into ZIP (city, state) values ('Detroit', 'Michigan');
insert into ZIP (city, state) values ('Visalia', 'California');
insert into ZIP (city, state) values ('Corpus Christi', 'Texas');
insert into ZIP (city, state) values ('Kansas City', 'Missouri');
insert into ZIP (city, state) values ('Appleton', 'Wisconsin');
insert into ZIP (city, state) values ('Chicago', 'Illinois');
insert into ZIP (city, state) values ('Detroit', 'Michigan');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('Huntsville', 'Alabama');
insert into ZIP (city, state) values ('Memphis', 'Tennessee');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Reno', 'Nevada');
insert into ZIP (city, state) values ('Knoxville', 'Tennessee');
insert into ZIP (city, state) values ('Pasadena', 'California');
insert into ZIP (city, state) values ('Grand Forks', 'North Dakota');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Wilmington', 'Delaware');
insert into ZIP (city, state) values ('Salem', 'Oregon');
insert into ZIP (city, state) values ('Moreno Valley', 'California');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Sioux Falls', 'South Dakota');
insert into ZIP (city, state) values ('Jacksonville', 'Florida');
insert into ZIP (city, state) values ('Huntington', 'West Virginia');
insert into ZIP (city, state) values ('Raleigh', 'North Carolina');
insert into ZIP (city, state) values ('Stamford', 'Connecticut');
insert into ZIP (city, state) values ('Monticello', 'Minnesota');
insert into ZIP (city, state) values ('Austin', 'Texas');
insert into ZIP (city, state) values ('Salt Lake City', 'Utah');
insert into ZIP (city, state) values ('Odessa', 'Texas');
insert into ZIP (city, state) values ('North Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Fort Myers', 'Florida');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Tulsa', 'Oklahoma');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Roanoke', 'Virginia');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Charleston', 'South Carolina');
insert into ZIP (city, state) values ('Richmond', 'California');
insert into ZIP (city, state) values ('Columbia', 'South Carolina');
insert into ZIP (city, state) values ('Detroit', 'Michigan');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Wilmington', 'Delaware');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Raleigh', 'North Carolina');
insert into ZIP (city, state) values ('Charleston', 'South Carolina');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Springfield', 'Illinois');
insert into ZIP (city, state) values ('Indianapolis', 'Indiana');
insert into ZIP (city, state) values ('Pasadena', 'California');
insert into ZIP (city, state) values ('Delray Beach', 'Florida');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Henderson', 'Nevada');
insert into ZIP (city, state) values ('Asheville', 'North Carolina');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Frankfort', 'Kentucky');
insert into ZIP (city, state) values ('Augusta', 'Georgia');
insert into ZIP (city, state) values ('Yonkers', 'New York');
insert into ZIP (city, state) values ('Corpus Christi', 'Texas');
insert into ZIP (city, state) values ('Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Monticello', 'Minnesota');
insert into ZIP (city, state) values ('West Palm Beach', 'Florida');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Kansas City', 'Kansas');
insert into ZIP (city, state) values ('Huntington', 'West Virginia');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Anderson', 'South Carolina');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Toledo', 'Ohio');
insert into ZIP (city, state) values ('Richmond', 'Virginia');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Boston', 'Massachusetts');
insert into ZIP (city, state) values ('Galveston', 'Texas');
insert into ZIP (city, state) values ('Lawrenceville', 'Georgia');
insert into ZIP (city, state) values ('Rochester', 'New York');
insert into ZIP (city, state) values ('Oakland', 'California');
insert into ZIP (city, state) values ('Gastonia', 'North Carolina');
insert into ZIP (city, state) values ('Jacksonville', 'Florida');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Cincinnati', 'Ohio');
insert into ZIP (city, state) values ('Macon', 'Georgia');
insert into ZIP (city, state) values ('Tulsa', 'Oklahoma');
insert into ZIP (city, state) values ('Salem', 'Oregon');
insert into ZIP (city, state) values ('Cincinnati', 'Ohio');
insert into ZIP (city, state) values ('Knoxville', 'Tennessee');
insert into ZIP (city, state) values ('Pittsburgh', 'Pennsylvania');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('Abilene', 'Texas');
insert into ZIP (city, state) values ('Fort Worth', 'Texas');
insert into ZIP (city, state) values ('Richmond', 'Virginia');
insert into ZIP (city, state) values ('Glendale', 'California');
insert into ZIP (city, state) values ('Waco', 'Texas');
insert into ZIP (city, state) values ('Daytona Beach', 'Florida');
insert into ZIP (city, state) values ('Monticello', 'Minnesota');
insert into ZIP (city, state) values ('Spokane', 'Washington');
insert into ZIP (city, state) values ('Huntington', 'West Virginia');
insert into ZIP (city, state) values ('New Orleans', 'Louisiana');
insert into ZIP (city, state) values ('Abilene', 'Texas');
insert into ZIP (city, state) values ('Memphis', 'Tennessee');
insert into ZIP (city, state) values ('Chattanooga', 'Tennessee');
insert into ZIP (city, state) values ('Reno', 'Nevada');
insert into ZIP (city, state) values ('Virginia Beach', 'Virginia');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Cincinnati', 'Ohio');
insert into ZIP (city, state) values ('Lincoln', 'Nebraska');
insert into ZIP (city, state) values ('Monroe', 'Louisiana');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Spartanburg', 'South Carolina');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Greenville', 'South Carolina');
insert into ZIP (city, state) values ('Kansas City', 'Missouri');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Lynchburg', 'Virginia');
insert into ZIP (city, state) values ('New Orleans', 'Louisiana');
insert into ZIP (city, state) values ('Paterson', 'New Jersey');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Austin', 'Texas');
insert into ZIP (city, state) values ('South Bend', 'Indiana');
insert into ZIP (city, state) values ('Saint Joseph', 'Missouri');
insert into ZIP (city, state) values ('Pasadena', 'California');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('New Hyde Park', 'New York');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Yonkers', 'New York');
insert into ZIP (city, state) values ('Indianapolis', 'Indiana');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Orlando', 'Florida');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Young America', 'Minnesota');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Austin', 'Texas');
insert into ZIP (city, state) values ('White Plains', 'New York');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('Minneapolis', 'Minnesota');
insert into ZIP (city, state) values ('Columbus', 'Ohio');
insert into ZIP (city, state) values ('Oakland', 'California');
insert into ZIP (city, state) values ('Oakland', 'California');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Fresno', 'California');
insert into ZIP (city, state) values ('Stamford', 'Connecticut');
insert into ZIP (city, state) values ('Anaheim', 'California');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Loretto', 'Minnesota');
insert into ZIP (city, state) values ('Anchorage', 'Alaska');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Kansas City', 'Kansas');
insert into ZIP (city, state) values ('Bakersfield', 'California');
insert into ZIP (city, state) values ('Kansas City', 'Missouri');
insert into ZIP (city, state) values ('Lynn', 'Massachusetts');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('San Luis Obispo', 'California');
insert into ZIP (city, state) values ('Sandy', 'Utah');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Santa Barbara', 'California');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('El Paso', 'Texas');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('Long Beach', 'California');
insert into ZIP (city, state) values ('Salt Lake City', 'Utah');
insert into ZIP (city, state) values ('Hialeah', 'Florida');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Seminole', 'Florida');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Stamford', 'Connecticut');
insert into ZIP (city, state) values ('Concord', 'California');
insert into ZIP (city, state) values ('Indianapolis', 'Indiana');
insert into ZIP (city, state) values ('Omaha', 'Nebraska');
insert into ZIP (city, state) values ('Lakewood', 'Washington');
insert into ZIP (city, state) values ('Irvine', 'California');
insert into ZIP (city, state) values ('Jamaica', 'New York');
insert into ZIP (city, state) values ('Rochester', 'New York');
insert into ZIP (city, state) values ('Eugene', 'Oregon');
insert into ZIP (city, state) values ('Amarillo', 'Texas');
insert into ZIP (city, state) values ('Glendale', 'Arizona');
insert into ZIP (city, state) values ('New York City', 'New York');
insert into ZIP (city, state) values ('Oklahoma City', 'Oklahoma');
insert into ZIP (city, state) values ('Baltimore', 'Maryland');
insert into ZIP (city, state) values ('Memphis', 'Tennessee');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Baton Rouge', 'Louisiana');
insert into ZIP (city, state) values ('Charlotte', 'North Carolina');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Charleston', 'West Virginia');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Des Moines', 'Iowa');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Shreveport', 'Louisiana');
insert into ZIP (city, state) values ('Madison', 'Wisconsin');
insert into ZIP (city, state) values ('Seattle', 'Washington');
insert into ZIP (city, state) values ('Loretto', 'Minnesota');
insert into ZIP (city, state) values ('Columbia', 'South Carolina');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Fresno', 'California');
insert into ZIP (city, state) values ('Burbank', 'California');
insert into ZIP (city, state) values ('San Jose', 'California');
insert into ZIP (city, state) values ('Wilmington', 'Delaware');
insert into ZIP (city, state) values ('Lincoln', 'Nebraska');
insert into ZIP (city, state) values ('Decatur', 'Georgia');
insert into ZIP (city, state) values ('Salt Lake City', 'Utah');
insert into ZIP (city, state) values ('Rochester', 'New York');
insert into ZIP (city, state) values ('Fort Wayne', 'Indiana');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Portland', 'Oregon');
insert into ZIP (city, state) values ('Arlington', 'Virginia');
insert into ZIP (city, state) values ('Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('Worcester', 'Massachusetts');
insert into ZIP (city, state) values ('Pueblo', 'Colorado');
insert into ZIP (city, state) values ('Baton Rouge', 'Louisiana');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Pompano Beach', 'Florida');
insert into ZIP (city, state) values ('Lynn', 'Massachusetts');
insert into ZIP (city, state) values ('Savannah', 'Georgia');
insert into ZIP (city, state) values ('Cincinnati', 'Ohio');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Mc Keesport', 'Pennsylvania');
insert into ZIP (city, state) values ('Montgomery', 'Alabama');
insert into ZIP (city, state) values ('Modesto', 'California');
insert into ZIP (city, state) values ('Tucson', 'Arizona');
insert into ZIP (city, state) values ('Evansville', 'Indiana');
insert into ZIP (city, state) values ('Brooklyn', 'New York');
insert into ZIP (city, state) values ('Delray Beach', 'Florida');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('Lake Worth', 'Florida');
insert into ZIP (city, state) values ('Boston', 'Massachusetts');
insert into ZIP (city, state) values ('Fort Myers', 'Florida');
insert into ZIP (city, state) values ('Champaign', 'Illinois');
insert into ZIP (city, state) values ('Amarillo', 'Texas');
insert into ZIP (city, state) values ('Saint Petersburg', 'Florida');
insert into ZIP (city, state) values ('Boulder', 'Colorado');
insert into ZIP (city, state) values ('Albany', 'New York');
insert into ZIP (city, state) values ('Jamaica', 'New York');
insert into ZIP (city, state) values ('Spokane', 'Washington');
insert into ZIP (city, state) values ('Shreveport', 'Louisiana');
insert into ZIP (city, state) values ('Milwaukee', 'Wisconsin');
insert into ZIP (city, state) values ('Denver', 'Colorado');
insert into ZIP (city, state) values ('Flint', 'Michigan');
insert into ZIP (city, state) values ('Odessa', 'Texas');
insert into ZIP (city, state) values ('Huntington', 'West Virginia');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Lancaster', 'Pennsylvania');
insert into ZIP (city, state) values ('Waco', 'Texas');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Omaha', 'Nebraska');
insert into ZIP (city, state) values ('Portland', 'Oregon');
insert into ZIP (city, state) values ('Tulsa', 'Oklahoma');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('Fairfield', 'Connecticut');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Philadelphia', 'Pennsylvania');
insert into ZIP (city, state) values ('Newark', 'New Jersey');
insert into ZIP (city, state) values ('Salt Lake City', 'Utah');
insert into ZIP (city, state) values ('Austin', 'Texas');
insert into ZIP (city, state) values ('Fort Myers', 'Florida');
insert into ZIP (city, state) values ('Jackson', 'Mississippi');
insert into ZIP (city, state) values ('Tyler', 'Texas');
insert into ZIP (city, state) values ('Newark', 'New Jersey');
insert into ZIP (city, state) values ('Springfield', 'Illinois');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Reno', 'Nevada');
insert into ZIP (city, state) values ('Fort Lauderdale', 'Florida');
insert into ZIP (city, state) values ('Cleveland', 'Ohio');
insert into ZIP (city, state) values ('Stockton', 'California');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Migrate', 'Kentucky');
insert into ZIP (city, state) values ('Henderson', 'Nevada');
insert into ZIP (city, state) values ('Van Nuys', 'California');
insert into ZIP (city, state) values ('Jackson', 'Mississippi');
insert into ZIP (city, state) values ('Hialeah', 'Florida');
insert into ZIP (city, state) values ('Atlanta', 'Georgia');
insert into ZIP (city, state) values ('Miami', 'Florida');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('Charlotte', 'North Carolina');
insert into ZIP (city, state) values ('Silver Spring', 'Maryland');
insert into ZIP (city, state) values ('Memphis', 'Tennessee');
insert into ZIP (city, state) values ('Los Angeles', 'California');
insert into ZIP (city, state) values ('San Jose', 'California');
insert into ZIP (city, state) values ('Carson City', 'Nevada');
insert into ZIP (city, state) values ('Sacramento', 'California');
insert into ZIP (city, state) values ('Phoenix', 'Arizona');
insert into ZIP (city, state) values ('Salt Lake City', 'Utah');
insert into ZIP (city, state) values ('Orlando', 'Florida');
insert into ZIP (city, state) values ('Mobile', 'Alabama');
insert into ZIP (city, state) values ('Tucson', 'Arizona');
insert into ZIP (city, state) values ('Richmond', 'Virginia');
insert into ZIP (city, state) values ('Montpelier', 'Vermont');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Memphis', 'Tennessee');
insert into ZIP (city, state) values ('Saint Louis', 'Missouri');
insert into ZIP (city, state) values ('Colorado Springs', 'Colorado');
insert into ZIP (city, state) values ('Madison', 'Wisconsin');
insert into ZIP (city, state) values ('Bethesda', 'Maryland');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('Rochester', 'New York');
insert into ZIP (city, state) values ('San Jose', 'California');
insert into ZIP (city, state) values ('Jackson', 'Mississippi');
insert into ZIP (city, state) values ('Grand Rapids', 'Michigan');
insert into ZIP (city, state) values ('Bradenton', 'Florida');
insert into ZIP (city, state) values ('Naples', 'Florida');
insert into ZIP (city, state) values ('Sioux Falls', 'South Dakota');
insert into ZIP (city, state) values ('Roanoke', 'Virginia');
insert into ZIP (city, state) values ('San Diego', 'California');
insert into ZIP (city, state) values ('Kansas City', 'Missouri');
insert into ZIP (city, state) values ('Jackson', 'Mississippi');
insert into ZIP (city, state) values ('Omaha', 'Nebraska');
insert into ZIP (city, state) values ('Pasadena', 'California');
insert into ZIP (city, state) values ('Albuquerque', 'New Mexico');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Battle Creek', 'Michigan');
insert into ZIP (city, state) values ('Warren', 'Michigan');
insert into ZIP (city, state) values ('San Jose', 'California');
insert into ZIP (city, state) values ('Dallas', 'Texas');
insert into ZIP (city, state) values ('Bakersfield', 'California');
insert into ZIP (city, state) values ('Tucson', 'Arizona');
insert into ZIP (city, state) values ('Houston', 'Texas');
insert into ZIP (city, state) values ('Louisville', 'Kentucky');
insert into ZIP (city, state) values ('San Francisco', 'California');
insert into ZIP (city, state) values ('Frankfort', 'Kentucky');
insert into ZIP (city, state) values ('Fresno', 'California');
insert into ZIP (city, state) values ('Ridgely', 'Maryland');
insert into ZIP (city, state) values ('Bakersfield', 'California');
insert into ZIP (city, state) values ('Las Vegas', 'Nevada');
insert into ZIP (city, state) values ('New Orleans', 'Louisiana');
insert into ZIP (city, state) values ('North Hollywood', 'California');
insert into ZIP (city, state) values ('Chico', 'California');
insert into ZIP (city, state) values ('Midland', 'Michigan');
insert into ZIP (city, state) values ('Scottsdale', 'Arizona');
insert into ZIP (city, state) values ('Rockford', 'Illinois');
insert into ZIP (city, state) values ('Washington', 'District of Columbia');
insert into ZIP (city, state) values ('San Antonio', 'Texas');
insert into ZIP (city, state) values ('Glendale', 'California');
insert into ZIP (city, state) values ('Bethesda', 'Maryland');
insert into ZIP (city, state) values ('Newport News', 'Virginia');
